const creds = require('../../test/data/credentials')
const LandingPage = require('../../src/pageobjects/LandingPage')
const LoginPage = require('../../src/pageobjects/LoginPage')
const HomePage = require('../../src/pageobjects/HomePage')
const MarketsPage = require('../../src/pageobjects/MarketsPage')
const AssetDetailsPage = require('../../src/pageobjects/AssetDetailsPage')
const PortfolioPage = require('../../src/pageobjects/PortfolioPage')
const PositionDetailsPage = require('../../src/pageobjects/PositionDetailsPage')
const Toasts = require('../../src/pageobjects/components/Toasts')
const ProfileIcon = require('../../src/pageobjects/components/ProfileIcon')

describe('USD-JPY Pair Trading Flow', () => {
    it('Should complete trading workflow', async () => {
        await LandingPage.goToLoginByCoordinates()
        await LoginPage.login(creds.email, creds.password)
        await HomePage.openMarkets()
        await MarketsPage.openUsdJpyPair()
        await AssetDetailsPage.sellAmount5000()
        await Toasts.expectOpenSuccess()
        await PortfolioPage.open()
        await PortfolioPage.dismissTooltip()
        await PortfolioPage.validateAmount5000()
        await PortfolioPage.openUSDJPYPosition()
        await PositionDetailsPage.closePosition()
        await Toasts.expectCloseSuccess()
        await PortfolioPage.verifyNoPositions()
        await ProfileIcon.logout()
        await LoginPage.verifyLoginPage()
    })
})
